parameters:
    ldap_role_mappings:
        ROLE_MEDIAPACKAGE:  "Webserver-MediaPackageMaintainers"
        ROLE_FEATURED:      "Webserver-FeaturedProgramsMaintainers"
        ROLE_APPROVE:       "Webserver-AppApprovers"
        ROLE_SUPER_ADMIN:   "Webserver-Administrators"
        ROLE_GAMEJAM_ADMIN: "Webserver-GameJam-Administrators"


security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
#        # for convenience, I decided to gather Sonata roles here
#        ROLE_SONATA_FOO_READER:
#            - ROLE_SONATA_ADMIN_DEMO_FOO_LIST
#            - ROLE_SONATA_ADMIN_DEMO_FOO_VIEW
#        ROLE_SONATA_FOO_EDITOR:
#            - ROLE_SONATA_ADMIN_DEMO_FOO_CREATE
#            - ROLE_SONATA_ADMIN_DEMO_FOO_EDIT
#        ROLE_SONATA_FOO_ADMIN:
#            - ROLE_SONATA_ADMIN_DEMO_FOO_DELETE
#            - ROLE_SONATA_ADMIN_DEMO_FOO_EXPORT
        # those are the roles I will use (less verbose)
        ROLE_ADMIN:         [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_FEATURED:
            - ROLE_CATROWEBADMIN_BLOCK_FEATURED_PROGRAM_ADMIN
            - ROLE_CATROWEBADMIN_BLOCK_FEATURED_URL_ADMIN
            - ROLE_CATROWEBADMIN_BLOCK_PROGRAMS_CATEGORIES_ADMIN
            - ROLE_ADMIN
        ROLE_APPROVE:
            - ROLE_CATROWEBADMIN_BLOCK_PROGRAMS_ALL_ADMIN
            - ROLE_CATROWEBADMIN_BLOCK_PROGRAMS_APPROVE_ADMIN
            - ROLE_CATROWEBADMIN_BLOCK_PROGRAMS_REPORTED_ADMIN
            - ROLE_CATROWEBADMIN_BLOCK_PROGRAMS_COMMENTS_ADMIN
            - ROLE_ADMIN
        ROLE_MEDIAPACKAGE:
            - ROLE_CATROWEBADMIN_BLOCK_MEDIAPACKAGE_FILE_ADMIN
            - ROLE_CATROWEBADMIN_BLOCK_MEDIAPACKAGE_CATEGORY_ADMIN
            - ROLE_CATROWEBADMIN_BLOCK_MEDIAPACKAGE_PACKAGE_ADMIN
            - ROLE_ADMIN
        ROLE_GAMEJAM_ADMIN:
            - ROLE_CATROWEBADMIN_BLOCK_USERS_LIMITED_ADMIN
            - ROLE_CATROWEBADMIN_BLOCK_GAMEJAM_ADMIN
            - ROLE_CATROWEBADMIN_BLOCK_GAMEJAM_SUBMITTED_ADMIN
            - ROLE_ADMIN

    providers:
        chain_provider:
            chain:
               providers: [fos_userbundle, fr3d_ldapbundle]
        fos_userbundle:
            id: fos_user.user_provider.username
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
            
    firewalls:
        api_checktoken:
            provider: chain_provider
            pattern: ^.*/api/checkToken/check.json
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator

        api_check_notifications:
            provider: chain_provider
            pattern: ^.*/api/notifications/get.json
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator

#        api_upload:
#            provider: chain_provider
#            pattern: ^.*/api/upload/upload.json
#            stateless: true
#            simple_preauth:
#                authenticator: apikey_authenticator
        api_submit:
            provider: chain_provider
            pattern: ^.*/api/gamejam/submit.json
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            
        debug:
            provider: chain_provider
            pattern: ^/debug
            security: false

        main:
            pattern:     ^/
            provider: chain_provider
            fr3d_ldap:  ~
            form_login:
                login_path: /login
                check_path: fos_user_security_check
                default_target_path: /
            logout: true
            anonymous:    true
            remember_me:
                name: remember_me
                secret: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
                secure: false
                httponly: false
            logout_on_user_change: true # remove when symfony 4

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            provider: chain_provider
            fr3d_ldap:  ~
            security: false
            form_login:
                always_use_default_target_path: true
                default_target_path: /profile
            logout:       true
            anonymous:    true


    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }


    acl:
        connection: default

